<?php
/**
 * Created by PhpStorm.
 * User: Volodymyr
 * Date: 11.07.2019
 * Time: 14:21
 */

namespace app\components;
use app\models\Category;
use yii\base\Widget;
use Yii;

class MenuWidget extends Widget
{
    public $tpl;
    public $data;
    public $tree;
    public $menuHTML;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if($this->tpl === null){
            $this->tpl = 'menu';
        }
        $this->tpl .= '.php';

    }

    public function run()
    {
        // get cache
        if($this->tpl == 'menu.php') {
            $menu = Yii::$app->cache->get('menu');
            if($menu) return $menu;
        }

        $this->data = Category::find()->indexBy('id')->asArray()->all();
        $this->tree = $this->getTree();
        $this->menuHTML = $this->getMenuHtml($this->tree);
        //set cache
        Yii::$app->cache->set('menu', $this->menuHTML, 60);
        return $this->menuHTML;

    }

    protected function getTree(){
        $tree = [];
        foreach ($this->data as $id=>&$node){
            if (!$node['parent_id'])
                $tree[$id] = &$node;
            else
                $this->data[$node['parent_id']]['children'][$node['id']] = &$node;
        }
        return $tree;
    }

    protected  function getMenuHtml($tree){
        $str = '';
        foreach ($tree as $category) {
            $str .= $this->catToTemplate($category);
        }
        return $str;
    }

    protected function catToTemplate($category){
        ob_start();
        include __DIR__ . '/menu_tpl/' . $this->tpl;
        return ob_get_clean();
    }

}